# Generated by Django 6.0.1 on 2026-02-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuremetadata",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
